In [2]:
install.packages("matlib")
install.packages("expm")
install.packages("ca")

Installing package into 'C:/Users/stryc/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)

also installing the dependencies 'numDeriv', 'SparseM', 'MatrixModels', 'minqa', 'nloptr', 'RcppEigen', 'htmlwidgets', 'carData', 'abind', 'pbkrtest', 'quantreg', 'maptools', 'lme4', 'xtable', 'rgl', 'car'





  There are binary versions available but the source versions are later:
         binary source needs_compilation
nloptr    2.0.0  2.0.1              TRUE
quantreg   5.88   5.93              TRUE
car      3.0-12 3.0-13             FALSE

  Binaries will be installed
package 'numDeriv' successfully unpacked and MD5 sums checked
package 'SparseM' successfully unpacked and MD5 sums checked
package 'MatrixModels' successfully unpacked and MD5 sums checked
package 'minqa' successfully unpacked and MD5 sums checked
package 'nloptr' successfully unpacked and MD5 sums checked
package 'RcppEigen' successfully unpacked and MD5 sums checked
package 'htmlwidgets' successfully unpacked and MD5 sums checked
package 'carData' successfully unpacked and MD5 sums checked
package 'abind' successfully unpacked and MD5 sums checked
package 'pbkrtest' successfully unpacked and MD5 sums checked
package 'quantreg' successfully unpacked and MD5 sums checked
package 'maptools' successfully unpacked and MD5 sum

installing the source package 'car'


Installing package into 'C:/Users/stryc/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)



package 'expm' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\stryc\AppData\Local\Temp\RtmpO6usK2\downloaded_packages


Installing package into 'C:/Users/stryc/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)



package 'ca' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\stryc\AppData\Local\Temp\RtmpO6usK2\downloaded_packages


In [3]:
#remove.packages("rlang")
remove.packages("dplyr")

install.packages("rlang")
install.packages("dplyr")

#library(rlang)
library(dplyr)

Removing package from 'C:/Users/stryc/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)

Installing package into 'C:/Users/stryc/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)



package 'rlang' successfully unpacked and MD5 sums checked


Warning message:
"cannot remove prior installation of package 'rlang'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem z kopiowaniem C:\Users\stryc\OneDrive\Documents\R\win-library\4.0\00LOCK\rlang\libs\x64\rlang.dll do C:\Users\stryc\OneDrive\Documents\R\win-library\4.0\rlang\libs\x64\rlang.dll: Permission denied"
Warning message:
"restored 'rlang'"



The downloaded binary packages are in
	C:\Users\stryc\AppData\Local\Temp\Rtmp4KM7JF\downloaded_packages


Installing package into 'C:/Users/stryc/OneDrive/Documents/R/win-library/4.0'
(as 'lib' is unspecified)

also installing the dependencies 'rlang', 'vctrs'





  There is a binary version available but the source version is later:
      binary source needs_compilation
dplyr  1.0.8  1.0.9              TRUE

  Binaries will be installed
package 'rlang' successfully unpacked and MD5 sums checked


Warning message:
"cannot remove prior installation of package 'rlang'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem z kopiowaniem C:\Users\stryc\OneDrive\Documents\R\win-library\4.0\00LOCK\rlang\libs\x64\rlang.dll do C:\Users\stryc\OneDrive\Documents\R\win-library\4.0\rlang\libs\x64\rlang.dll: Permission denied"
Warning message:
"restored 'rlang'"


package 'vctrs' successfully unpacked and MD5 sums checked


Warning message:
"cannot remove prior installation of package 'vctrs'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem z kopiowaniem C:\Users\stryc\OneDrive\Documents\R\win-library\4.0\00LOCK\vctrs\libs\x64\vctrs.dll do C:\Users\stryc\OneDrive\Documents\R\win-library\4.0\vctrs\libs\x64\vctrs.dll: Permission denied"
Warning message:
"restored 'vctrs'"


package 'dplyr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\stryc\AppData\Local\Temp\Rtmp4KM7JF\downloaded_packages


Warning message:
"package 'dplyr' was built under R version 4.0.5"


ERROR: Error: package or namespace load failed for 'dplyr' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace 'rlang' 0.4.10 is already loaded, but >= 1.0.0 is required


In [26]:
data

[,1] [,2] [,3] [,4]
[1,] 32   44    60   70 
[2,] 22   38   104  125 
[3,] 13   48    61  113 
[4,]  3   18    54   96

In [52]:
?ca

In [54]:
library(matlib)
library(expm)
library(ca)

data <- matrix(c(32, 22, 13, 3, 44, 38, 48, 18, 60, 104, 61, 54, 70, 125, 113, 96), nrow = 4)

n <- sum(data)

freq <- data/n
freq


count_row_massess <- function(data) {
  rows <- numeric(nrow(data))
  for (i in 1:nrow(data)) {
    rows[i] <- sum(data[i, ])
  }
  rows
}

count_col_massess <- function(data) {
  cols <- numeric(ncol(data))
  for (i in 1:ncol(data)) {
    cols[i] <- sum(data[, i])
  }
  cols
}


r <- count_row_massess(freq)
c <- count_col_massess(freq)

Dr <- diag(length(r)) * r
Dc <- diag(length(c)) * c



# Macierz profili wierszowych
R = inv(Dr)%*%freq

# Macierz profili kolumnowych
C = inv(Dc)%*%freq


#Dekompozycja według wartośi osobliwych
#Najpierw birzemy pierwiastek z wartości dla Dr i Dc i dopiero później odwrotność macierzy
A <- solve(Dr ^ (1/2)) %*% (freq - r %*% t(c)) %*% solve(Dc ^ (1/2))
A

sv <- svd(A)
gamm <- diag(length(sv$d)) * sv$d
U <- sv$u
V <- sv$v


F <- solve(Dr ^ (1/2)) %*% U %*% gamm

G <- solve(Dc ^ (1/2)) %*% V %*% gamm





[,1]        [,2]       [,3]       [,4]      
[1,] 0.035516093 0.04883463 0.06659267 0.07769145
[2,] 0.024417314 0.04217536 0.11542730 0.13873474
[3,] 0.014428413 0.05327414 0.06770255 0.12541620
[4,] 0.003329634 0.01997780 0.05993341 0.10654828

[,1]         [,2]        [,3]         [,4]       
[1,]  0.133203867  0.05819913 -0.015805310 -0.07753757
[2,] -0.003183739 -0.04579816  0.051097476 -0.01341809
[3,] -0.040991673  0.05039544 -0.045963056  0.02475694
[4,] -0.094008538 -0.06341766  0.004801831  0.07352502

In [19]:
F <- solve(Dr ^ (0.5)) %*% U %*% gamm
F

[,1]        [,2]         [,3]        [,4]        
[1,] -0.34543922 -0.002507134  0.02175994 1.196627e-17
[2,]  0.02998446 -0.117785342 -0.02235324 1.196627e-17
[3,]  0.04182549  0.156690466 -0.01811548 1.196627e-17
[4,]  0.30798818 -0.013250444  0.03646010 1.196627e-17

In [24]:
?solve

In [55]:
#Do sprawdzenia czy te wartości powinny być takie same? Raczej tak i nie wiem dlaczego nie wychodzą...
ca(freq)
F
G



 Principal inertias (eigenvalues):
           1       2        3       
Value      0.04603 0.010888 0.000606
Percentage 80.02%  18.93%   1.05%   


 Rows:
             [,1]      [,2]     [,3]      [,4]
Mass     0.228635  0.320755 0.260821  0.189789
ChiDist  0.346133  0.123580 0.163185  0.310422
Inertia  0.027392  0.004899 0.006946  0.018288
Dim. 1  -1.610093  0.139758 0.194949  1.435534
Dim. 2  -0.024027 -1.128781 1.501624 -0.126984


 Columns:
             [,1]      [,2]      [,3]     [,4]
Mass     0.077691  0.164262  0.309656 0.448391
ChiDist  0.603235  0.270804  0.127025 0.165024
Inertia  0.028271  0.012046  0.004996 0.012211
Dim. 1  -2.770459 -0.955385  0.122621 0.745341
Dim. 2  -0.884667  1.673293 -1.171059 0.349022

[,1]        [,2]         [,3]        [,4]        
[1,] -0.34543922 -0.002507134  0.02175994 1.196627e-17
[2,]  0.02998446 -0.117785342 -0.02235324 1.196627e-17
[3,]  0.04182549  0.156690466 -0.01811548 1.196627e-17
[4,]  0.30798818 -0.013250444  0.03646010 1.196627e-17

[,1]       [,2]       [,3]        [,4]         
[1,] -0.5943912 -0.0923127  0.04549626 -1.196627e-17
[2,] -0.2049741  0.1746038 -0.02887773 -1.196627e-17
[3,]  0.0263079 -0.1221969 -0.02260959 -1.196627e-17
[4,]  0.1599100  0.0364195  0.01831000 -1.196627e-17

In [25]:
?ca